### ISSUE TITLE
gap in b/w prompt and cursor

### ISSUE THREAD

**Issue by kamrajx** [connectbot/connectbot.github.io#159]
![Screenshot_20230816-071906_ConnectBot](https://github.com/connectbot/connectbot.github.io/assets/36145513/dd16e3a9-c91e-4b85-bed5-45ca36e96dcf)

**Comment by woodenshoe-wi** [comment]
I think this is a font issue.

I ran into it when I installed the latest version from F-Droid on my new Motorola/Android 13 phone.  The same version of ConnectBot works fine on my older Motorola/Android 9 phone.

ConnectBot doesn't seem to have a setting to choose fonts, but Markor (also from F-Droid app) does let me choose fonts and I found out that the "monospace" font wasn't really monospace when the Android System font style was set to "Default".  After changing the Android System font style to "Android", the "monospace" font is a true monospace font and the problem went away.

Two other true monospace fonts installed on my phone are Liberation Mono (Courier New), and Source Pro Code.  I don't know how common it is for the default monospace font to not be truly monospace, but maybe being able to choose the font would be helpful?
