### ISSUE TITLE
Landscape mode only supports one direction

### ISSUE THREAD

**Issue by schultzter** [connectbot/connectbot.github.io#35]
When I rotate my tablet into landscape I have to rotate it so that the home key is on the right. If I rotate it so that the home key is on the left then ConnectBot is upside down!

The reason I would prefer to rotate it left is so the tablet fits into my bluetooth keyboard's holder. If I rotate the tablet right then I need to find another way to support the tablet while I use the keyboard (which is kind of silly because the keyboard has a stand that would normally hold the tablet). 

Other apps support rotating the tablet in either direction.

Thanks

**Comment by ozbek** [comment]
Hi,

You need to post app related issues here: https://github.com/connectbot/connectbot/issues

**Comment by schultzter** [comment]
Done

**Comment by ozbek** [comment]
Awesome! Please close this one then :)
