### ISSUE TITLE
Specify ssh port to connect to

### ISSUE THREAD

**Issue by znikola** [connectbot/connectbot.github.io#63]
Is there a way to specify an ssh port to which to connect to?
I have a server that's not running on the standard ssh 22 port.

**Comment by ozbek** [comment]
You should probably use the [project's repo](https://github.com/connectbot/connectbot) to file issues, this repo is for the project's website.

To answer the question: Yes, you can specify any port. Just press the down button right to the host address for details. Or you may simply type the address as shown in the hint. (i.e., `username@hostname:port`)

![image](https://user-images.githubusercontent.com/452620/67395734-70c64700-f5e1-11e9-89ef-0b833fd07732.png)

V

![image](https://user-images.githubusercontent.com/452620/67395756-79b71880-f5e1-11e9-9733-07ddd6e892f4.png)

**Comment by znikola** [comment]
Thank you for your answer, and sorry about opening the issue in a wrong place.
